package com.jeff.everyboo.cms.entity;
// Generated 2018-11-6 15:20:46 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShopBillTrade generated by hbm2java
 */
@Entity
@Table(name = "shop_bill_trade", catalog = "everyboo")
public class ShopBillTrade implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int type;
	private String tradePhone;
	private int count;
	private int tradeStatus;
	private Date createDate;
	private String createBy;

	public ShopBillTrade() {
	}

	public ShopBillTrade(int userId, int type, String tradePhone, int count) {
		this.userId = userId;
		this.type = type;
		this.tradePhone = tradePhone;
		this.count = count;
	}

	public ShopBillTrade(int userId, int type, String tradePhone, int count, int tradeStatus, Date createDate,
			String createBy) {
		this.userId = userId;
		this.type = type;
		this.tradePhone = tradePhone;
		this.count = count;
		this.tradeStatus = tradeStatus;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "trade_phone", length = 16)
	public String getTradePhone() {
		return this.tradePhone;
	}

	public void setTradePhone(String tradePhone) {
		this.tradePhone = tradePhone;
	}

	@Column(name = "count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	@Column(name = "trade_status")
	public int getTradeStatus() {
		return this.tradeStatus;
	}

	public void setTradeStatus(int tradeStatus) {
		this.tradeStatus = tradeStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

}
