package com.jeff.everyboo.cms.entity;
// Generated 2018-11-6 15:20:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ShopUserExt generated by hbm2java
 */
@Entity
@Table(name = "shop_user_ext", catalog = "everyboo")
public class ShopUserExt implements java.io.Serializable {

	private Integer id;
	@JsonIgnore
	private ShopUser shopUser;
	private BigDecimal credits;  //购物积分
	private BigDecimal bill;	//共享上限（通过购买商品提高）
	private BigDecimal activeBill;	//共享积分(平台分红)
	private BigDecimal tradeBill;	//广告上限（直推奖+间推奖+管理奖最高值  购买商品提高上限）
	private BigDecimal balance;	//消费积分(充值)
	private BigDecimal tuiguang;	//广告积分（直推奖+间推奖+管理奖）
	private String bankOwer;
	private String bankCard;
	private String bankDeposit;
	private Date createDate;
	private String createBy;
	private Date updateDate;
	private String updateBy;

	@Override
	public String toString() {
		return "ShopUserExt [id=" + id + ", credits=" + credits + ", bill=" + bill + ", activeBill=" + activeBill
				+ ", tradeBill=" + tradeBill + ", balance=" + balance + ", createDate=" + createDate + ", createBy="
				+ createBy + ", updateDate=" + updateDate + ", updateBy=" + updateBy + "]";
	}

	public ShopUserExt() {
	}

	public ShopUserExt(ShopUser shopUser, BigDecimal credits, BigDecimal bill, BigDecimal activeBill) {
		this.shopUser = shopUser;
		this.credits = credits;
		this.bill = bill;
		this.activeBill = activeBill;
	}

	public ShopUserExt(Integer id, BigDecimal credits, BigDecimal bill, BigDecimal activeBill, BigDecimal tradeBill, BigDecimal balance,
			Date createDate, String createBy, Date updateDate, String updateBy) {
		super();
		this.id = id;
		this.credits = credits;
		this.bill = bill;
		this.activeBill = activeBill;
		this.tradeBill = tradeBill;
		this.balance = balance;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public ShopUserExt(ShopUser shopUser, BigDecimal credits, BigDecimal bill, BigDecimal activeBill, BigDecimal tradeBill,
			BigDecimal balance, Date createDate, String createBy, Date updateDate, String updateBy) {
		this.shopUser = shopUser;
		this.credits = credits;
		this.bill = bill;
		this.activeBill = activeBill;
		this.tradeBill = tradeBill;
		this.balance = balance;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public ShopUser getShopUser() {
		return this.shopUser;
	}

	public void setShopUser(ShopUser shopUser) {
		this.shopUser = shopUser;
	}

	@Column(name = "credits", length = 12)
	public BigDecimal getCredits() {
		return this.credits;
	}

	public void setCredits(BigDecimal credits) {
		this.credits = credits;
	}

	@Column(name = "bill",  length = 12)
	public BigDecimal getBill() {
		return this.bill;
	}

	public void setBill(BigDecimal bill) {
		this.bill = bill;
	}

	@Column(name = "active_bill", length = 12)
	public BigDecimal getActiveBill() {
		return this.activeBill;
	}

	public void setActiveBill(BigDecimal activeBill) {
		this.activeBill = activeBill;
	}

	@Column(name = "trade_bill", length = 12)
	public BigDecimal getTradeBill() {
		return this.tradeBill;
	}

	public void setTradeBill(BigDecimal tradeBill) {
		this.tradeBill = tradeBill;
	}

	@Column(name = "balance", length = 12)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "bank_ower")
	public String getBankOwer() {
		return bankOwer;
	}

	public void setBankOwer(String bankOwer) {
		this.bankOwer = bankOwer;
	}
	@Column(name = "bank_card")
	public String getBankCard() {
		return bankCard;
	}

	public void setBankCard(String bankCard) {
		this.bankCard = bankCard;
	}
	@Column(name = "bank_deposit")
	public String getBankDeposit() {
		return bankDeposit;
	}

	public void setBankDeposit(String bankDeposit) {
		this.bankDeposit = bankDeposit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_by", length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	
	@Column(name = "tuiguang", length = 12)
	public BigDecimal getTuiguang() {
		return tuiguang;
	}

	public void setTuiguang(BigDecimal tuiguang) {
		this.tuiguang = tuiguang;
	}


}
