package com.jeff.everyboo.cms.entity;
// Generated 2018-11-9 10:43:37 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ShopTrade generated by hbm2java
 */
@Entity
@Table(name = "shop_trade", catalog = "everyboo")
public class ShopTradeUser implements java.io.Serializable {

	private Integer id;
	private String tradeNo;
	private int userId;
	private int jtype;
	private BigDecimal price;
	private int status;
	private int credits;
	private Date createDate;
	@JsonIgnore
	private String account;
	@JsonIgnore
	private String phone;
	@JsonIgnore
	private String bankOwer;
	@JsonIgnore
	private String bankCard;

	public ShopTradeUser() {
	}


	public ShopTradeUser(Integer id, String tradeNo, int userId, int jtype, BigDecimal price, int status, int credits,
			Date createDate, String account, String phone) {
		super();
		this.id = id;
		this.tradeNo = tradeNo;
		this.userId = userId;
		this.jtype = jtype;
		this.price = price;
		this.status = status;
		this.credits = credits;
		this.createDate = createDate;
		this.account = account;
		this.phone = phone;
	}
	
	


	public ShopTradeUser(Integer id, String tradeNo, int userId, int jtype, BigDecimal price, int status, int credits,
			Date createDate, String account, String phone, String bankOwer, String bankCard) {
		super();
		this.id = id;
		this.tradeNo = tradeNo;
		this.userId = userId;
		this.jtype = jtype;
		this.price = price;
		this.status = status;
		this.credits = credits;
		this.createDate = createDate;
		this.account = account;
		this.phone = phone;
		this.bankOwer = bankOwer;
		this.bankCard = bankCard;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "trade_no", nullable = false, length = 32)
	public String getTradeNo() {
		return this.tradeNo;
	}

	public void setTradeNo(String tradeNo) {
		this.tradeNo = tradeNo;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "type", nullable = false)
	public int getJtype() {
		return this.jtype;
	}

	public void setJtype(int type) {
		this.jtype = type;
	}

	@Column(name = "price", nullable = false)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "status")
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "credits")
	public int getCredits() {
		return this.credits;
	}

	public void setCredits(int credits) {
		this.credits = credits;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getAccount() {
		return account;
	}


	public void setAccount(String account) {
		this.account = account;
	}


	public String getPhone() {
		return phone;
	}


	public void setPhone(String phone) {
		this.phone = phone;
	}


	public String getBankOwer() {
		return bankOwer;
	}


	public void setBankOwer(String bankOwer) {
		this.bankOwer = bankOwer;
	}


	public String getBankCard() {
		return bankCard;
	}


	public void setBankCard(String bankCard) {
		this.bankCard = bankCard;
	}
	
}
