package com.jeff.everyboo.cms.entity;
// Generated 2018-11-6 15:20:46 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShopRegisterRule generated by hbm2java
 */
@Entity
@Table(name = "shop_register_rule", catalog = "everyboo")
public class ShopRegisterRule implements java.io.Serializable {

	private Integer id;
	private String vipLevel;
	private int ztjkljhs;
	private int jtjkljhs;
	private String ztj;
	private String jtj;
	private String glj;
	private String gufen;
	private String bill;
	private Date createDate;
	private String createBy;
	private Date updateDate;
	private String updateBy;
	private String fugoufd;
	private String fugouztfd;
	private String fugoujtfd;
	private String fenhong;

	public ShopRegisterRule() {
	}

	public ShopRegisterRule(String vipLevel, int ztjkljhs, int jtjkljhs) {
		this.vipLevel = vipLevel;
		this.ztjkljhs = ztjkljhs;
		this.jtjkljhs = jtjkljhs;
	}

	public ShopRegisterRule(String vipLevel, int ztjkljhs, int jtjkljhs, String ztj, String jtj, String glj,
			String gufen, String bill, Date createDate, String createBy, Date updateDate, String updateBy,
			String fugoufd, String fugouztfd, String fugoujtfd,String fenhong) {
		this.vipLevel = vipLevel;
		this.ztjkljhs = ztjkljhs;
		this.jtjkljhs = jtjkljhs;
		this.ztj = ztj;
		this.jtj = jtj;
		this.glj = glj;
		this.gufen = gufen;
		this.bill = bill;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.fugoufd = fugoufd;
		this.fugouztfd = fugouztfd;
		this.fugoujtfd = fugoujtfd;
		this.fenhong = fenhong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "vip_level", nullable = false, length = 8)
	public String getVipLevel() {
		return this.vipLevel;
	}

	public void setVipLevel(String vipLevel) {
		this.vipLevel = vipLevel;
	}

	@Column(name = "ztjkljhs", nullable = false)
	public int getZtjkljhs() {
		return this.ztjkljhs;
	}

	public void setZtjkljhs(int ztjkljhs) {
		this.ztjkljhs = ztjkljhs;
	}

	@Column(name = "jtjkljhs", nullable = false)
	public int getJtjkljhs() {
		return this.jtjkljhs;
	}

	public void setJtjkljhs(int jtjkljhs) {
		this.jtjkljhs = jtjkljhs;
	}

	@Column(name = "ztj", length = 8)
	public String getZtj() {
		return this.ztj;
	}

	public void setZtj(String ztj) {
		this.ztj = ztj;
	}

	@Column(name = "jtj", length = 8)
	public String getJtj() {
		return this.jtj;
	}

	public void setJtj(String jtj) {
		this.jtj = jtj;
	}

	@Column(name = "glj", length = 8)
	public String getGlj() {
		return this.glj;
	}

	public void setGlj(String glj) {
		this.glj = glj;
	}

	@Column(name = "gufen", length = 8)
	public String getGufen() {
		return this.gufen;
	}

	public void setGufen(String gufen) {
		this.gufen = gufen;
	}

	@Column(name = "bill", length = 8)
	public String getBill() {
		return this.bill;
	}

	public void setBill(String bill) {
		this.bill = bill;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_by", length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "fugoufd", length = 8)
	public String getFugoufd() {
		return this.fugoufd;
	}

	public void setFugoufd(String fugoufd) {
		this.fugoufd = fugoufd;
	}

	@Column(name = "fugouztfd", length = 8)
	public String getFugouztfd() {
		return this.fugouztfd;
	}

	public void setFugouztfd(String fugouztfd) {
		this.fugouztfd = fugouztfd;
	}

	@Column(name = "fugoujtfd", length = 8)
	public String getFugoujtfd() {
		return this.fugoujtfd;
	}

	public void setFugoujtfd(String fugoujtfd) {
		this.fugoujtfd = fugoujtfd;
	}

	public String getFenhong() {
		return fenhong;
	}
	@Column(name = "fenhong", length = 8)
	public void setFenhong(String fenhong) {
		this.fenhong = fenhong;
	}

}
