package com.jeff.everyboo.cms.entity;
// Generated 2018-12-8 15:50:28 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShopProfit generated by hbm2java
 */
@Entity
@Table(name = "shop_profit", catalog = "everyboo")
public class ShopProfit implements java.io.Serializable {

	private Integer id;
	private byte type;
	private BigDecimal profit;
	private String dateString;
	private Date createDate;

	public ShopProfit() {
	}

	public ShopProfit(byte type, BigDecimal profit) {
		this.type = type;
		this.profit = profit;
	}

	public ShopProfit(byte type, BigDecimal profit, String dateString, Date createDate) {
		this.type = type;
		this.profit = profit;
		this.dateString = dateString;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	@Column(name = "profit", nullable = false, precision = 10)
	public BigDecimal getProfit() {
		return this.profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}

	@Column(name = "date_string", length = 8)
	public String getDateString() {
		return this.dateString;
	}

	public void setDateString(String dateString) {
		this.dateString = dateString;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
