package com.jeff.everyboo.cms.entity;
// Generated 2018-11-19 18:41:10 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShopSysParam generated by hbm2java
 */
@Entity
@Table(name = "shop_sys_param", catalog = "everyboo")
public class ShopSysParam implements java.io.Serializable {

	private Integer id;
	private String sysCode;
	private String sysType;
	private String sysValue;
	private String sysDesc;
	private Date updateDate;
	private Date createDate;

	public ShopSysParam() {
	}

	public ShopSysParam(String sysCode, String sysType, String sysValue) {
		this.sysCode = sysCode;
		this.sysType = sysType;
		this.sysValue = sysValue;
	}

	public ShopSysParam(String sysCode, String sysType, String sysValue, Date updateDate, Date createDate) {
		this.sysCode = sysCode;
		this.sysType = sysType;
		this.sysValue = sysValue;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sys_code", nullable = false, length = 12)
	public String getSysCode() {
		return this.sysCode;
	}

	public void setSysCode(String sysCode) {
		this.sysCode = sysCode;
	}

	@Column(name = "sys_type", nullable = false, length = 4)
	public String getSysType() {
		return this.sysType;
	}

	public void setSysType(String sysType) {
		this.sysType = sysType;
	}

	@Column(name = "sys_value", nullable = false, length = 24)
	public String getSysValue() {
		return this.sysValue;
	}

	public void setSysValue(String sysValue) {
		this.sysValue = sysValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "sys_desc", length = 64)
	public String getSysDesc() {
		return sysDesc;
	}

	public void setSysDesc(String sysDesc) {
		this.sysDesc = sysDesc;
	}

}
